// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgXnff6qSdQTiJnnse9X0f7QXOH0vPy5w',
    appId: '1:725750656943:web:c10a2681827b53ab9b895a',
    messagingSenderId: '725750656943',
    projectId: 'clearsky-95c39',
    authDomain: 'clearsky-95c39.firebaseapp.com',
    storageBucket: 'clearsky-95c39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHr2T1LFcTL5egplW6cTMXsgnXEpZXomc',
    appId: '1:725750656943:android:8812c7aee3f983f89b895a',
    messagingSenderId: '725750656943',
    projectId: 'clearsky-95c39',
    storageBucket: 'clearsky-95c39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZOHGhXLGOVfzmpFy5Xl0bfGbu184sZoc',
    appId: '1:725750656943:ios:d2c99c70d8df0cab9b895a',
    messagingSenderId: '725750656943',
    projectId: 'clearsky-95c39',
    storageBucket: 'clearsky-95c39.firebasestorage.app',
    iosClientId: '725750656943-r7dsj8rmno69gpkf5o0eorr6o89v2k4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.towerCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZOHGhXLGOVfzmpFy5Xl0bfGbu184sZoc',
    appId: '1:725750656943:ios:d2c99c70d8df0cab9b895a',
    messagingSenderId: '725750656943',
    projectId: 'clearsky-95c39',
    storageBucket: 'clearsky-95c39.firebasestorage.app',
    iosClientId: '725750656943-r7dsj8rmno69gpkf5o0eorr6o89v2k4t.apps.googleusercontent.com',
    iosBundleId: 'com.example.towerCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgXnff6qSdQTiJnnse9X0f7QXOH0vPy5w',
    appId: '1:725750656943:web:a1db98bba661b5c29b895a',
    messagingSenderId: '725750656943',
    projectId: 'clearsky-95c39',
    authDomain: 'clearsky-95c39.firebaseapp.com',
    storageBucket: 'clearsky-95c39.firebasestorage.app',
  );
}
